spring.application.name=clientes
server.port=8082
# Corrección de datasource (con C)
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=1004034391
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Corrección de JPA y Hibernate (ddl con L, show-sql y platform)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect